# Generated by Django 4.1.7 on 2023-03-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('price', models.FloatField(default=100)),
                ('brand', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
